###############################################################################
# [WISOv3 초기 schema 스크립트]
###############################################################################

-- 0. 세션 트랜잭션 설정
 SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED;

-- 0.CREATE DATABASE WISOv3
-- DROP DATABASE IF EXISTS WISOv3;
-- CREATE DATABASE WISOv3 character SET utf8mb4 collate utf8mb4_general_ci;
-- COMMIT;

SET foreign_key_checks = 0;

-- CREATE TABLE USER
DROP TABLE IF EXISTS WISOv3.USER;
CREATE TABLE WISOv3.`USER`
(
  `id` int NOT NULL AUTO_INCREMENT,
  `kakao_token` varchar(200) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `name` varchar(15) COLLATE utf8mb4_general_ci NOT NULL,
  `email` varchar(200) COLLATE utf8mb4_general_ci NOT NULL,
  `password` varchar(300) COLLATE utf8mb4_general_ci NOT NULL,
  `mobile_number` varchar(11) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `regist_datetime` datetime(6) NOT NULL,
  `update_datetime` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `USR_KAKAO_ID` (`kakao_token`),
  UNIQUE KEY `USR_EMAIL` (`email`),
  UNIQUE KEY `USR_MOBILE_NUMBER` (`mobile_number`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- create TABLE MOVE_CATEGORY
DROP TABLE IF EXISTS WISOv3.MOVE_CATEGORY;
CREATE TABLE WISOv3.`MOVE_CATEGORY` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;

-- create TABLE MOVE_RESERVATION
DROP TABLE IF EXISTS WISOv3.MOVE_RESERVATION;
CREATE TABLE WISOv3.`MOVE_RESERVATION` (
  `id` int NOT NULL AUTO_INCREMENT,
  `address` varchar(250) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `mobile_number` varchar(100) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `regist_datetime` datetime(6) NOT NULL,
  `update_datetime` datetime(6) NOT NULL,
  `MOVE_CATEGORY_id` int NOT NULL,
  `USER_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `MOVE_RESERVATION_FK_MOVE_CATEGORY_id` (`MOVE_CATEGORY_id`),
  KEY `MOVE_RESERVATION_FK_USER_id` (`USER_id`),
  CONSTRAINT `MOVE_RESERVATION_FK_MOVE_CATEGORY_id` FOREIGN KEY (`MOVE_CATEGORY_id`) REFERENCES `MOVE_CATEGORY` (`id`),
  CONSTRAINT `MOVE_RESERVATION_FK_USER_id` FOREIGN KEY (`USER_id`) REFERENCES `USER` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE STATUS
DROP TABLE IF EXISTS WISOv3.STATUS;
CREATE TABLE WISOv3.`STATUS` (
  `id` int NOT NULL AUTO_INCREMENT,
  `status` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE SERVICE_DAY_OF_WEEK
DROP TABLE IF EXISTS WISOv3.SERVICE_DAY_OF_WEEK;
CREATE TABLE WISOv3.`SERVICE_DAY_OF_WEEK` (
  `id` int NOT NULL AUTO_INCREMENT,
  `service_day_of_week` varchar(50) COLLATE utf8mb4_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE SERVICE_STARTING_TIME
DROP TABLE IF EXISTS WISOv3.SERVICE_STARTING_TIME;
CREATE TABLE `SERVICE_STARTING_TIME` (
  `id` int NOT NULL AUTO_INCREMENT,
  `starting_time` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE SERVICE_DURATION
DROP TABLE IF EXISTS WISOv3.SERVICE_DURATION;
CREATE TABLE `SERVICE_DURATION` (
  `id` int NOT NULL AUTO_INCREMENT,
  `service_duration` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE RESERVE_CYCLE
DROP TABLE IF EXISTS WISOv3.RESERVE_CYCLE;
CREATE TABLE WISOv3.`RESERVE_CYCLE` (
  `id` int NOT NULL AUTO_INCREMENT,
  `reserve_cycle` varchar(50) COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE HOUSECLEANING_RESERVATION_SERVICE_DAY_OF_WEEK
DROP TABLE IF EXISTS WISOv3.HOUSECLEANING_RESERVATION_SERVICE_DAY_OF_WEEK;
CREATE TABLE WISOv3.`HOUSECLEANING_RESERVATION_SERVICE_DAY_OF_WEEK` (
  `id` int NOT NULL AUTO_INCREMENT,
  `HOUSECLEANING_RESERVATION_id` int DEFAULT NULL,
  `SERVICE_DAY_OF_WEEK_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `HOUSECLEANING_RESERV_SERVICE_DOW_FK_HOUSECLEANING_RESERVATION_id` (`HOUSECLEANING_RESERVATION_id`),
  KEY `HOUSECLEANING_RESERV_SERVICE_DOW_FK_SERVICE_DAY_OF_WEEK_id` (`SERVICE_DAY_OF_WEEK_id`),
  CONSTRAINT `HOUSECLEANING_RESERV_SERVICE_DOW_FK_HOUSECLEANING_RESERVATION_id` FOREIGN KEY (`HOUSECLEANING_RESERVATION_id`) REFERENCES `HOUSECLEANING_RESERVATION` (`id`),
  CONSTRAINT `HOUSECLEANING_RESERV_SERVICE_DOW_FK_SERVICE_DAY_OF_WEEK_id` FOREIGN KEY (`SERVICE_DAY_OF_WEEK_id`) REFERENCES `SERVICE_DAY_OF_WEEK` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE SERVICE_DURATION_SERVICE_STATING_TIME
DROP TABLE IF EXISTS WISOv3.SERVICE_DURATION_SERVICE_STATING_TIME;
CREATE TABLE `SERVICE_DURATION_SERVICE_STATING_TIME` (
  `id` int NOT NULL AUTO_INCREMENT,
  `SERVICE_DURATION_id` int DEFAULT NULL,
  `SERVICE_STARTING_TIME_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `SERVICE_DRT_SERVICE_ST_FK_SERVICE_DURATION_id` (`SERVICE_DURATION_id`),
  KEY `SERVICE_DRT_SERVICE_ST_FK_SERVICE_STARTING_TIME_id` (`SERVICE_STARTING_TIME_id`),
  CONSTRAINT `SERVICE_DRT_SERVICE_ST_FK_SERVICE_DURATION_id` FOREIGN KEY (`SERVICE_DURATION_id`) REFERENCES `SERVICE_DURATION` (`id`),
  CONSTRAINT `SERVICE_DRT_SERVICE_ST_FK_SERVICE_STARTING_TIME_id` FOREIGN KEY (`SERVICE_STARTING_TIME_id`) REFERENCES `SERVICE_STARTING_TIME` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- CREATE TABLE HOUSECLEANING_RESERVATION
DROP TABLE IF EXISTS WISOv3.HOUSECLEANING_RESERVATION;
CREATE TABLE WISOv3.`HOUSECLEANING_RESERVATION` (
  `id` int NOT NULL AUTO_INCREMENT,
  `service_start_date` date NOT NULL,
  `reserve_location` varchar(300) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `have_pet` tinyint(1) DEFAULT NULL,
  `regist_datetime` datetime(6) NOT NULL,
  `update_datetime` datetime(6) NOT NULL,
  `RESERVE_CYCLE_id` int DEFAULT NULL,
  `SERVICE_DURATION_id` int DEFAULT NULL,
  `SERVICE_STARTING_TIME_id` int DEFAULT NULL,
  `STATUS_id` int DEFAULT NULL,
  `USER_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `HOUSECLEANING_RESERVATION_FK_RESERVE_CYCLE_id` (`RESERVE_CYCLE_id`),
  KEY `HOUSECLEANING_RESERVATION_FK_SERVICE_DURATION_id` (`SERVICE_DURATION_id`),
  KEY `HOUSECLEANING_RESERVATION_FK_SERVICE_STARTING_TIME_id` (`SERVICE_STARTING_TIME_id`),
  KEY `HOUSECLEANING_RESERVATION_FK_STATUS_id` (`STATUS_id`),
  KEY `HOUSECLEANING_RESERVATION_FK_USER_id` (`USER_id`),
  CONSTRAINT `HOUSECLEANING_RESERVATION_FK_RESERVE_CYCLE_id` FOREIGN KEY (`RESERVE_CYCLE_id`) REFERENCES `RESERVE_CYCLE` (`id`),
  CONSTRAINT `HOUSECLEANING_RESERVATION_FK_SERVICE_DURATION_id` FOREIGN KEY (`SERVICE_DURATION_id`) REFERENCES `SERVICE_DURATION` (`id`),
  CONSTRAINT `HOUSECLEANING_RESERVATION_FK_SERVICE_STARTING_TIME_id` FOREIGN KEY (`SERVICE_STARTING_TIME_id`) REFERENCES `SERVICE_STARTING_TIME` (`id`),
  CONSTRAINT `HOUSECLEANING_RESERVATION_FK_STATUS_id` FOREIGN KEY (`STATUS_id`) REFERENCES `STATUS` (`id`),
  CONSTRAINT `HOUSECLEANING_RESERVATION_FK_USER_id` FOREIGN KEY (`USER_id`) REFERENCES `USER` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
COMMIT;


-- Status table
INSERT INTO STATUS(status) VALUES('예약완료');

INSERT INTO STATUS(status) VALUES('예약취소');

INSERT INTO STATUS(status) VALUES('결제완료');

INSERT INTO STATUS(status) VALUES('결제취소');
COMMIT;


-- ServiceStartingTimes table
INSERT INTO SERVICE_STARTING_TIME(starting_time) VALUES('오전9시');

INSERT INTO SERVICE_STARTING_TIME(starting_time) VALUES('오전10시');

INSERT INTO SERVICE_STARTING_TIME(starting_time) VALUES('오후2시');
COMMIT;


-- ServiceDurations table
INSERT INTO SERVICE_DURATION(service_duration) VALUES('3시간');

INSERT INTO SERVICE_DURATION(service_duration) VALUES('4시간');

INSERT INTO SERVICE_DURATION(service_duration) VALUES('8시간');
COMMIT;


-- ServiceDayOfWeeks table
INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('월');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('화');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('수');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('목');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('금');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('토');

INSERT INTO SERVICE_DAY_OF_WEEK(service_day_of_week) VALUES('일');
COMMIT;


-- ReserveCycles table
INSERT INTO RESERVE_CYCLE(reserve_cycle) VALUES('1회');

INSERT INTO RESERVE_CYCLE(reserve_cycle) VALUES('매주');

INSERT INTO RESERVE_CYCLE(reserve_cycle) VALUES('2주');

INSERT INTO RESERVE_CYCLE(reserve_cycle) VALUES('4주');
COMMIT;


-- SERVICE_DURATION_SERVICE_STATING_TIME table
INSERT INTO SERVICE_DURATION_SERVICE_STATING_TIME(SERVICE_DURATION_id, SERVICE_STARTING_TIME_id) VALUES('1','2');

INSERT INTO SERVICE_DURATION_SERVICE_STATING_TIME(SERVICE_DURATION_id, SERVICE_STARTING_TIME_id) VALUES('1','3');

INSERT INTO SERVICE_DURATION_SERVICE_STATING_TIME(SERVICE_DURATION_id, SERVICE_STARTING_TIME_id) VALUES('2','1');

INSERT INTO SERVICE_DURATION_SERVICE_STATING_TIME(SERVICE_DURATION_id, SERVICE_STARTING_TIME_id) VALUES('2','2');

INSERT INTO SERVICE_DURATION_SERVICE_STATING_TIME(SERVICE_DURATION_id, SERVICE_STARTING_TIME_id) VALUES('3','1');
COMMIT;


-- Move_categories table
INSERT INTO MOVE_CATEGORY(name) VALUES('가정이사');

INSERT INTO MOVE_CATEGORY(name) VALUES('소형이사');

INSERT INTO MOVE_CATEGORY(name) VALUES('사무실이사');
COMMIT;